language: python
python:
  - "3.8"
install:
  - pip install pytest pytest-cov coveralls flake8
  - pip install -r requirements.txt
script:
  - flake8 .
  - pytest --cov=cvxportfolio/
after_success:
  - coveralls
